name: flotilla3
dependencies:
- backports=1.0=py35_0
- cycler=0.10.0=py35_0
- cython=0.24=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- flake8=2.5.1=py35_0
- fontconfig=2.11.1=5
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- joblib=0.9.4=py35_0
- jsonschema=2.4.0=py35_0
- jupyter_client=4.2.2=py35_0
- jupyter_core=4.1.0=py35_0
- libgfortran=3.0=0
- libpng=1.6.17=0
- libsodium=1.0.3=0
- libxml2=2.9.2=0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np111py35_0
- mccabe=0.3.1=py35_0
- mistune=0.7.2=py35_0
- mkl=11.3.1=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- networkx=1.11=py35_0
- nose=1.3.7=py35_0
- notebook=4.2.0=py35_0
- numpy=1.11.0=py35_0
- openssl=1.0.2g=0
- pandas=0.18.0=np111py35_0
- path.py=8.2.1=py35_0
- patsy=0.4.1=py35_0
- pep8=1.7.0=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- ptyprocess=0.5=py35_0
- py=1.4.31=py35_0
- pyflakes=1.1.0=py35_0
- pygments=2.1.3=py35_0
- pymongo=3.0.3=py35_0
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_1
- pytest=2.9.1=py35_0
- python=3.5.1=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- pyyaml=3.11=py35_1
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- readline=6.2=2
- scikit-learn=0.17.1=np111py35_0
- scipy=0.17.0=np111py35_2
- seaborn=0.7.0=py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- statsmodels=0.6.1=np111py35_0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zeromq=4.1.3=0
- zlib=1.2.8=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - brewer2mpl==1.4.1
  - coverage==4.0.3
  - gspread==0.3.0
  - husl==4.0.3
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-core==4.1.0
  - pytest-cov==2.2.1
  - python-coveralls==2.7.0
  - requests==2.9.1
  - semantic-version==2.5.0
  - sh==1.11

